active_modules:
  Bender_isoCHA425HV0:
    config_implementation:
      main:
        alarm_memory_enable: false
        always_publish_measurements: false
        chademo_mode: false
        delay_startup_device: 5
        delay_t_off_k1_k2: 5
        delay_t_on_k1_k2: 5
        imd_device_id: 3
        overvoltage_alarm_enable: false
        overvoltage_alarm_threshold_V: 1050
        r1_prealarm_kohm: 250
        r2_alarm_kohm: 100
        relais_r1_mode: false
        relais_r2_mode: false
        selftest_enable_at_start: true
        selftest_enable_gridconnection: false
        undervoltage_alarm_enable: false
        undervoltage_alarm_threshold_V: 30
    connections:
      serial_comm_hub:
        - implementation_id: main
          module_id: SerialCommHub0
    module: Bender_isoCHA425HV
  SerialCommHub0:
    config_implementation:
      main:
        baudrate: 115200
        ignore_echo: true
        initial_timeout_ms: 500
        max_packet_size: 256
        parity: 0
        retries: 2
        rtscts: false
        rxtx_gpio_chip: ''
        rxtx_gpio_line: 0
        rxtx_gpio_tx_high: false
        serial_port: /dev/ttyLP4
        within_message_timeout_ms: 100
    connections: {}
    module: SerialCommHub
  api:
    config_module:
      charger_information_file: ''
      hw_caps_max_current_export_decimal_places: 2
      hw_caps_max_current_export_round_to: 0
      hw_caps_max_current_import_decimal_places: 2
      hw_caps_max_current_import_round_to: 0
      hw_caps_max_plug_temperature_C_decimal_places: 2
      hw_caps_max_plug_temperature_C_round_to: 0
      hw_caps_min_current_export_decimal_places: 2
      hw_caps_min_current_export_round_to: 0
      hw_caps_min_current_import_decimal_places: 2
      hw_caps_min_current_import_round_to: 0
      limits_max_current_decimal_places: 2
      limits_max_current_round_to: 0
      powermeter_VAR_decimal_places: 2
      powermeter_VAR_round_to: 0
      powermeter_current_decimal_places: 2
      powermeter_current_round_to: 0
      powermeter_energy_export_decimal_places: 2
      powermeter_energy_export_round_to: 0
      powermeter_energy_import_decimal_places: 2
      powermeter_energy_import_round_to: 0
      powermeter_frequency_decimal_places: 2
      powermeter_frequency_round_to: 0
      powermeter_power_decimal_places: 2
      powermeter_power_round_to: 0
      powermeter_voltage_decimal_places: 2
      powermeter_voltage_round_to: 0
      telemetry_evse_temperature_C_decimal_places: 2
      telemetry_evse_temperature_C_round_to: 0
      telemetry_fan_rpm_decimal_places: 2
      telemetry_fan_rpm_round_to: 0
      telemetry_plug_temperature_C_decimal_places: 2
      telemetry_plug_temperature_C_round_to: 0
      telemetry_supply_voltage_12V_decimal_places: 2
      telemetry_supply_voltage_12V_round_to: 0
      telemetry_supply_voltage_minus_12V_decimal_places: 2
      telemetry_supply_voltage_minus_12V_round_to: 0
    connections:
      error_history:
        - implementation_id: error_history
          module_id: error_history
      evse_manager:
        - implementation_id: evse
          module_id: connector
    module: API
  auth:
    config_module:
      connection_timeout: 10
      ignore_connector_faults: false
      master_pass_group_id: ''
      prioritize_authorization_over_stopping_transaction: true
      selection_algorithm: PlugEvents
    connections:
      evse_manager:
        - implementation_id: evse
          module_id: connector
      token_provider:
        - implementation_id: main
          module_id: token_provider
      token_validator:
        - implementation_id: main
          module_id: token_validator
    module: Auth
  bsp:
    config_module:
      connector_type: IEC62196Type2Cable
      max_current_A: 80
      min_current_A: 6
      pt1000_1_identification: PT1000-1
      pt1000_2_identification: PT1000-2
      pt1000_3_identification: PT1000-3
      pt1000_4_identification: PT1000-4
      reset_active_low: true
      reset_gpio_line_name: nSAFETY_RESET_INT
      serial_debug: false
      serial_port: /dev/ttyLP2
      serial_trace: false
    connections: {}
    module: CbChargeSOMDriver
  connector:
    config_module:
      ac_enforce_hlc: false
      ac_hlc_enabled: false
      ac_hlc_use_5percent: false
      ac_nominal_voltage: 75
      ac_with_soc: false
      autocharge_use_slac_instead_of_hlc: false
      cable_check_enable_imd_self_test: true
      cable_check_wait_below_60V_before_finish: true
      cable_check_wait_number_of_imd_measurements: 1
      central_contract_validation_allowed: false
      charge_mode: DC
      connector_id: 1
      connector_type: Unknown
      contract_certificate_installation_enabled: true
      dbg_hlc_auth_after_tstep: false
      dc_isolation_voltage_V: 0
      disable_authentication: false
      enable_autocharge: false
      ev_receipt_required: false
      evse_id: US*CHB*E123456*1
      evse_id_din: 49A80737A45678
      external_ready_to_start_charging: false
      fail_on_powermeter_errors: true
      hack_allow_bpt_with_iso2: false
      hack_fix_hlc_integer_current_requests: false
      hack_pause_imd_during_precharge: false
      hack_present_current_offset: 0
      hack_simplified_mode_limit_10A: false
      hack_skoda_enyaq: false
      hack_sleep_in_cable_check: 0
      hack_sleep_in_cable_check_volkswagen: 0
      has_ventilation: true
      initial_meter_value_timeout_ms: 5000
      inoperative_error_use_vendor_id: false
      lock_connector_in_state_b: true
      logfile_suffix: session_uuid
      max_current_export_A: 6
      max_current_import_A: 6
      payment_enable_contract: true
      payment_enable_eim: true
      raise_mrec9: false
      request_zero_power_in_idle: false
      sae_j2847_2_bpt_enabled: false
      sae_j2847_2_bpt_mode: V2G
      session_id_type: UUID
      session_logging: true
      session_logging_path: /tmp/everest-logs
      session_logging_xml: false
      sleep_before_enabling_pwm_hlc_mode_ms: 500
      soft_over_current_measurement_noise_A: 0.5
      soft_over_current_timeout_ms: 7000
      soft_over_current_tolerance_percent: 10
      state_F_after_fault_ms: 300
      switch_3ph1ph_cp_state: X1
      switch_3ph1ph_delay_s: 10
      uk_smartcharging_random_delay_at_any_change: true
      uk_smartcharging_random_delay_enable: false
      uk_smartcharging_random_delay_max_duration: 600
      zero_power_allow_ev_to_ignore_pause: false
      zero_power_ignore_pause: false
    connections:
      bsp:
        - implementation_id: evse_board_support
          module_id: bsp
      hlc:
        - implementation_id: charger
          module_id: iso15118_charger
      imd:
        - implementation_id: main
          module_id: Bender_isoCHA425HV0
      powersupply_DC:
        - implementation_id: main
          module_id: powersupply_dc
      slac:
        - implementation_id: main
          module_id: evse_slac
    mapping:
      module:
        connector: 1
        evse: 1
    module: EvseManager
  energy_manager:
    config_module:
      debug: false
      nominal_ac_voltage: 75
      schedule_interval_duration: 60
      schedule_total_duration: 1
      slice_ampere: 0.5
      slice_watt: 500
      switch_3ph1ph_max_nr_of_switches_per_session: 0
      switch_3ph1ph_power_hysteresis_W: 200
      switch_3ph1ph_switch_limit_stickyness: DontChange
      switch_3ph1ph_time_hysteresis_s: 600
      switch_3ph1ph_while_charging_mode: Never
      update_interval: 1
    connections:
      energy_trunk:
        - implementation_id: energy_grid
          module_id: grid_connection_point
    module: EnergyManager
  error_history:
    config_implementation:
      error_history:
        database_path: /tmp/error_history.db
    connections: {}
    module: ErrorHistory
  evse_security:
    config_module:
      csms_ca_bundle: ca/csms/CSMS_ROOT_CA.pem
      csms_leaf_cert_directory: client/csms
      csms_leaf_key_directory: client/csms
      mf_ca_bundle: ca/mf/MF_ROOT_CA.pem
      mo_ca_bundle: ca/mo/MO_ROOT_CA.pem
      private_key_password: test1234
      secc_leaf_cert_directory: client/cso
      secc_leaf_key_directory: client/cso
      v2g_ca_bundle: ca/v2g/V2G_ROOT_CA.pem
    connections: {}
    module: EvseSecurity
  evse_slac:
    config_implementation:
      main:
        ac_mode_five_percent: false
        chip_reset_delay_ms: 100
        chip_reset_timeout_ms: 500
        debug_simulate_failed_matching: false
        device: eth1
        do_chip_reset: false
        link_status_detection: false
        link_status_retry_ms: 100
        link_status_timeout_ms: 10000
        number_of_sounds: 10
        publish_mac_on_first_parm_req: false
        publish_mac_on_match_cnf: true
        reset_instead_of_fail: true
        set_key_timeout_ms: 500
        sounding_attenuation_adjustment: 0
    connections: {}
    module: EvseSlac
  grid_connection_point:
    config_module:
      fuse_limit_A: 6
      phase_count: 3
    connections:
      energy_consumer:
        - implementation_id: energy_grid
          module_id: connector
    module: EnergyNode
  iso15118_charger:
    config_module:
      auth_timeout_eim: 300
      auth_timeout_pnc: 55
      device: eth1
      enable_sdp_server: true
      supported_DIN70121: true
      supported_ISO15118_2: true
      terminate_connection_on_failed_response: false
      tls_key_logging: false
      tls_key_logging_path: /tmp
      tls_security: prohibit
      tls_timeout: 15000
      verify_contract_cert_chain: false
    connections:
      security:
        - implementation_id: main
          module_id: evse_security
    module: EvseV2G
  powersupply_dc:
    config_module:
      can_device: can0
      controller_address: 240
      conversion_efficiency_export: 0.95
      device_connection_timeout_s: 15
      group_address: 1
      module_addresses: zero
    connections: {}
    module: InfyPower
  token_provider:
    config_implementation:
      main:
        connector_id: 0
        timeout: 10
        token: DEADBEEF
        type: RFID
    connections:
      evse:
        - implementation_id: evse
          module_id: connector
    module: DummyTokenProvider
  token_validator:
    config_implementation:
      main:
        sleep: 0.25
        validation_reason: Token seems valid
        validation_result: Accepted
    connections: {}
    module: DummyTokenValidator
'x-module-layout':
  Bender_isoCHA425HV0:
    position:
      x: -43
      y: -1
    terminals:
      bottom: []
      left:
        - id: serial_comm_hub
          interface: serial_communication_hub
          type: requirement
      right:
        - id: main
          interface: isolation_monitor
          type: provide
      top: []
  SerialCommHub0:
    position:
      x: -66
      y: 1
    terminals:
      bottom: []
      left: []
      right:
        - id: main
          interface: serial_communication_hub
          type: provide
      top: []
  api:
    position:
      x: 27
      y: -11
    terminals:
      bottom: []
      left:
        - id: error_history
          interface: error_history
          type: requirement
        - id: evse_energy_sink
          interface: external_energy_limits
          type: requirement
        - id: evse_manager
          interface: evse_manager
          type: requirement
        - id: ocpp
          interface: ocpp
          type: requirement
        - id: random_delay
          interface: uk_random_delay
          type: requirement
      right:
        - id: main
          interface: empty
          type: provide
      top: []
  auth:
    position:
      x: 74
      y: -7
    terminals:
      bottom: []
      left:
        - id: evse_manager
          interface: evse_manager
          type: requirement
        - id: kvs
          interface: kvs
          type: requirement
        - id: token_provider
          interface: auth_token_provider
          type: requirement
        - id: token_validator
          interface: auth_token_validator
          type: requirement
      right:
        - id: main
          interface: auth
          type: provide
        - id: reservation
          interface: reservation
          type: provide
      top: []
  bsp:
    position:
      x: -43
      y: -15
    terminals:
      bottom: []
      left: []
      right:
        - id: evse_board_support
          interface: evse_board_support
          type: provide
      top: []
  connector:
    position:
      x: -10
      y: -5
    terminals:
      bottom: []
      left:
        - id: ac_rcd
          interface: ac_rcd
          type: requirement
        - id: bsp
          interface: evse_board_support
          type: requirement
        - id: connector_lock
          interface: connector_lock
          type: requirement
        - id: hlc
          interface: ISO15118_charger
          type: requirement
        - id: imd
          interface: isolation_monitor
          type: requirement
        - id: powermeter_car_side
          interface: powermeter
          type: requirement
        - id: powermeter_grid_side
          interface: powermeter
          type: requirement
        - id: powersupply_DC
          interface: power_supply_DC
          type: requirement
        - id: slac
          interface: slac
          type: requirement
        - id: store
          interface: kvs
          type: requirement
      right:
        - id: energy_grid
          interface: energy
          type: provide
        - id: evse
          interface: evse_manager
          type: provide
        - id: random_delay
          interface: uk_random_delay
          type: provide
        - id: token_provider
          interface: auth_token_provider
          type: provide
      top: []
  energy_manager:
    position:
      x: 46
      y: -41
    terminals:
      bottom: []
      left:
        - id: energy_trunk
          interface: energy
          type: requirement
      right:
        - id: main
          interface: energy_manager
          type: provide
      top: []
  error_history:
    position:
      x: -10
      y: -12
    terminals:
      bottom: []
      left: []
      right:
        - id: error_history
          interface: error_history
          type: provide
      top: []
  evse_security:
    position:
      x: -66
      y: -8
    terminals:
      bottom: []
      left: []
      right:
        - id: main
          interface: evse_security
          type: provide
      top: []
  evse_slac:
    position:
      x: -43
      y: 13
    terminals:
      bottom: []
      left: []
      right:
        - id: main
          interface: slac
          type: provide
      top: []
  grid_connection_point:
    position:
      x: 26
      y: -33
    terminals:
      bottom: []
      left:
        - id: energy_consumer
          interface: energy
          type: requirement
        - id: powermeter
          interface: powermeter
          type: requirement
        - id: price_information
          interface: energy_price_information
          type: requirement
      right:
        - id: energy_grid
          interface: energy
          type: provide
        - id: external_limits
          interface: external_energy_limits
          type: provide
      top: []
  iso15118_charger:
    position:
      x: -43
      y: -8
    terminals:
      bottom: []
      left:
        - id: security
          interface: evse_security
          type: requirement
      right:
        - id: charger
          interface: ISO1S118_charger
          type: provide
      top: []
  powersupply_dc:
    position:
      x: -43
      y: 6
    terminals:
      bottom: []
      left: []
      right:
        - id: main
          interface: power_supply_DC
          type: provide
      top: []
  token_provider:
    position:
      x: 54
      y: -6
    terminals:
      bottom: []
      left:
        - id: evse
          interface: evse_manager
          type: requirement
      right:
        - id: main
          interface: auth_token_provider
          type: provide
      top: []
  token_validator:
    position:
      x: 54
      y: 1
    terminals:
      bottom: []
      left: []
      right:
        - id: main
          interface: auth_token_validator
          type: provide
      top: []
